In [25]:
import sys
import os
sys.path.append(os.getcwd())

from common.Stock import Stock
import common.constants as constants
from datetime import datetime, timedelta
import time
import yfinance as yf
import pandas as pd
import numpy as np
from common.helperFunctions import percentageChange

stock = {
            "name": "Varun Beverages Limited",
            "tradingsymbol": "APLAPOLLO",
            "instrument_token": 218
      }

In [ ]:
ticket = Stock(stock["name"], "^NSEI")
df = ticket.get_stock_price_data('2y','1D')
df

[*********************100%***********************]  1 of 1 completed
ERROR:yfinance:2025-07-31 00:00:28,935:multi.py:184:download:
1 Failed download:
ERROR:yfinance:2025-07-31 00:00:28,936:multi.py:197:download:['^NSEI.NS']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')

Empty DataFrame
Columns: [(Adj Close, ^NSEI.NS), (Close, ^NSEI.NS), (High, ^NSEI.NS), (Low, ^NSEI.NS), (Open, ^NSEI.NS), (Volume, ^NSEI.NS)]
Index: []

In [ ]:
df = yf.download("ABB.NS", period="2y", interval="1d")

df

[*********************100%***********************]  1 of 1 completed

Price             Close         High          Low         Open  Volume
Ticker           ABB.NS       ABB.NS       ABB.NS       ABB.NS  ABB.NS
Date
2023-07-31  4502.950195  4557.545992  4456.217546  4456.217546  254120
2023-08-01  4470.163086  4539.050373  4448.750234  4528.616081  119691
2023-08-02  4359.735352  4507.103901  4332.041933  4458.640419  217964
2023-08-03  4325.069336  4389.406889  4277.644163  4359.735369  195937
2023-08-04  4389.455566  4400.285863  4263.796888  4263.796888  199490
...                 ...          ...          ...          ...     ...
2025-07-24  5699.000000  5734.500000  5655.000000  5711.000000  116292
2025-07-25  5643.000000  5710.000000  5610.500000  5699.000000  340538
2025-07-28  5545.500000  5644.000000  5525.000000  5640.000000  265335
2025-07-29  5579.000000  5592.000000  5478.000000  5545.000000  209954
2025-07-30  5554.000000  5610.000000  5470.000000  5610.000000  331812

[494 rows x 5 columns]

In [4]:
DUMMY_API_KEY_ZERODHA = "dummy_api_key"
import pandas as pd
from zerodha.zerodha_connect import KiteConnect
enctoken="FtksKWoy4Uu2aJTK+dXfN3bqWDAK5/UsBbIXj5pzabX8TJc9HLJ/OIG1EvTRIz9jRrzJvv1wmDK+9dPCHk7HMWs1KgZoprFZlFzr1NfyCCSm4iVGlszHJw=="

kc = KiteConnect(DUMMY_API_KEY_ZERODHA, root="https://kite.zerodha.com/",  enctoken=enctoken)

df = pd.DataFrame(kc.instruments())
segment = df['segment'].unique()
segment
# stock_options= df[(df['segment'] == 'NFO-OPT')]
# stock_options

GeneralException: Route not found

In [2]:
stock_options= df[(df['segment'] == 'NFO-FUT')]
stock_options

,instrument_token,exchange_token,tradingsymbol,name,last_price,expiry,strike,tick_size,lot_size,instrument_type,segment,exchange
50702,13568258,53001,NIFTY25SEPFUT,NIFTY,0.0,2025-09-30,0.0,0.10,75,FUT,NFO-FUT,NFO
50703,13355010,52168,NIFTY25OCTFUT,NIFTY,0.0,2025-10-28,0.0,0.10,75,FUT,NFO-FUT,NFO
50704,9485826,37054,NIFTY25NOVFUT,NIFTY,0.0,2025-11-25,0.0,0.10,75,FUT,NFO-FUT,NFO
50705,13566722,52995,BANKNIFTY25SEPFUT,BANKNIFTY,0.0,2025-09-30,0.0,0.20,35,FUT,NFO-FUT,NFO
50706,13349122,52145,BANKNIFTY25OCTFUT,BANKNIFTY,0.0,2025-10-28,0.0,0.20,35,FUT,NFO-FUT,NFO
...,...,...,...,...,...,...,...,...,...,...,...,...
51337,13457666,52569,YESBANK25OCTFUT,YESBANK,0.0,2025-10-28,0.0,0.01,31100,FUT,NFO-FUT,NFO
51338,12587778,49171,YESBANK25NOVFUT,YESBANK,0.0,2025-11-25,0.0,0.01,31100,FUT,NFO-FUT,NFO
51339,13805058,53926,ZYDUSLIFE25SEPFUT,ZYDUSLIFE,0.0,2025-09-30,0.0,0.05,900,FUT,NFO-FUT,NFO
51340,13457922,52570,ZYDUSLIFE25OCTFUT,ZYDUSLIFE,0.0,2025-10-28,0.0,0.05,900,FUT,NFO-FUT,NFO
51341,12595458,49201,ZYDUSLIFE25NOVFUT,ZYDUSLIFE,0.0,2025-11-25,0.0,0.05,900,FUT,NFO-FUT,NFO

In [ ]:
zerodha = KiteConnect(DUMMY_API_KEY_ZERODHA, root="https://kite.zerodha.com/",  enctoken=enctoken)
zerodha.historical_data(13566722, "2025-08-21", "2025-08-30", "day", oi=False)

GeneralException: Route not found